name: Call Print Hello

on:
  workflow_dispatch:
    inputs:
      times:
        description: "Number of times to run the action"
        required: true
        default: "5"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::{\"number\":[$(seq 1 ${{ github.event.inputs.times }} | tr '\n' ',' | sed 's/,$//')]}"

  call-print-hello:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print Hello
        uses: ./.github/actions/print_hello
        with:
          number: ${{ matrix.number }}
